### ISSUE TITLE
Windows 10 Requests Installation of .NET Framework 3.5

### ISSUE THREAD

**Issue by OllyHill** [djhohnstein/SharpChrome#2]
I've been testing this and wanted to provide feedback. The program ran well on Windows 7 after compiling with Visual Studio 2019. No modifications to the code was made.

However, running the same build on Windows 10 Pro 18363 brings a pop-up to install .NET Framework 3.5. I recompiled the build, but changed the solution file to use .NET framework version 4. This new build runs on both Windows 7 and Windows 10 without any pop-ups to install different frameworks. Will changing the framework cause any issues?

This is a fantastic project and keep up the great work.

**Comment by djhohnstein** [comment]
Hey Olly,

Thanks for the kind words! As far as I know, so long as the project still compiles when re-targeting the solution, the binary should run without issue. At the time of the projects inception, 3.5 was reliably found across machines; however, as time marched onward, 4.0 became the defacto standard. The project _should_ be backwards compliant to 2.0 as well. If you ever have a question as to what version of .NET is installed, a quick way to do so is list the folders in `C:\Windows\Microsoft.NET\Framework64` and compile your projects according to the installed versions. 

Best of luck to you.
