### ISSUE TITLE
Not Compatible with Chrome 80

### ISSUE THREAD

**Issue by OllyHill** [djhohnstein/SharpChrome#4]
I always feel like I'm bothering you mate, but wanted to let you know this is no longer working. I think this occurred with Chrome version 80. Was wondering what your thoughts were and how to proceed?

Cheers,
Olly

**Comment by djhohnstein** [comment]
Hey Olly,

This project won't work under the newer version of Chrome starting with 80. AFAIK Chrome now encrypts an AES256 key that's used to encrypt the passwords. @harmj0y is working on implementing it in SharpDPAPI, at which point I'll shamelessly rip it out and update this project. 

In the mean time, Mimikatz offers the same functionality, you'll just need to tidy up the output. Hope that helps!
