### ISSUE TITLE
why?

### ISSUE THREAD

**Issue by xunnun** [djhohnstein/SharpChrome#5]
> If SharpChrome is run from a high integrity context (such as Administrator), it will retrieve Chrome data for each user with Chrome installed.

how yo retrieve all users ?

you code ?

**Comment by djhohnstein** [comment]
Ah, that's a legacy comment from the first rewrite when I didn't understand out DPAPI worked. Essentially, that was wrong and incorrect of me to say.

The readme has been updated with the latest push.
